services:
  postgres-db:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: hd
      PGPORT: 5432
