CREATE TABLE IF NOT EXISTS KNOWLEDGE.TB_KNOWLEDGE_TAG (
    FK_KNOWLEDGE INT NOT NULL,
    FK_TAG INT NOT NULL,
    CONSTRAINT PK_TB_KNOWLEDGE_TAG PRIMARY KEY (FK_KNOWLEDGE, FK_TAG) 
);
 
ALTER TABLE KNOWLEDGE.TB_KNOWLEDGE_TAG ADD CONSTRAINT FK_KNOWLEDGE
    FOREIGN KEY (FK_KNOWLEDGE)
    REFERENCES KNOWLEDGE.TB_KNOWLEDGE (ID);
 
ALTER TABLE KNOWLEDGE.TB_KNOWLEDGE_TAG ADD CONSTRAINT FK_TAG
    FOREIGN KEY (FK_TAG)
    REFERENCES KNOWLEDGE.TB_TAG (ID);
