CREATE TABLE CHAT.TB_SECTOR_USER_EMPLOYEE (
    FK_SECTOR SERIAL,
    FK_USER SERIAL,
    constraint PK_TB_SECTOR_USER_EMPLOYEE PRIMARY KEY (FK_SECTOR, FK_USER)
);

ALTER TABLE CHAT.TB_SECTOR_USER_EMPLOYEE ADD CONSTRAINT FK_SECTOR
    FOREIGN KEY (FK_SECTOR)
    REFERENCES CHAT.TB_SECTOR (ID);
 
ALTER TABLE CHAT.TB_SECTOR_USER_EMPLOYEE ADD CONSTRAINT FK_USER
    FOREIGN KEY (FK_USER)
    REFERENCES AUTH.TB_USER (ID);
