CREATE TABLE CHAT.TB_SECTOR_USER_CUSTOMER (
    FK_SECTOR SERIAL,
    FK_USER SERIAL,
    CONSTRAINT PK_TB_SECTOR_USER_CUSTOMER PRIMARY KEY (FK_SECTOR, FK_USER)
);

ALTER TABLE CHAT.TB_SECTOR_USER_CUSTOMER ADD CONSTRAINT FK_SECTOR
    FOREIGN KEY (FK_SECTOR)
    REFERENCES CHAT.TB_SECTOR (ID);
 
ALTER TABLE CHAT.TB_SECTOR_USER_CUSTOMER ADD CONSTRAINT FK_USER
    FOREIGN KEY (FK_USER)
    REFERENCES AUTH.TB_USER (ID);
