CREATE TABLE CHAT.TB_ROOM (
    ID SERIAL CONSTRAINT PK_TB_ROOM PRIMARY KEY,
    CODE SERIAL NOT NULL,
    FK_USER_CUSTOMER SERIAL,
    FK_USER_COMPANY SERIAL,
    FK_SECTOR SERIAL
);

ALTER TABLE CHAT.TB_ROOM ADD CONSTRAINT FK_SECTOR
    FOREIGN KEY (FK_SECTOR)
    REFERENCES CHAT.TB_SECTOR (ID);
 
ALTER TABLE CHAT.TB_ROOM ADD CONSTRAINT FK_USER_CUSTOMER
    FOREIGN KEY (FK_USER_CUSTOMER)
    REFERENCES AUTH.TB_USER (ID);
 
ALTER TABLE CHAT.TB_ROOM ADD CONSTRAINT FK_USER_COMPANY
    FOREIGN KEY (FK_USER_COMPANY)
    REFERENCES AUTH.TB_USER (ID);
