CREATE TABLE CHAT.TB_ROOM (
    ID SERIAL CONSTRAINT PK_TB_ROOM PRIMARY KEY,
    CODE SERIAL NOT NULL CONSTRAINT UC_TB_ROOM_CODE UNIQUE,
    FK_USER_CUSTOMER SERIAL NOT NULL,
    FK_USER_EMPLOYEE SERIAL,
    FK_SECTOR SERIAL NOT NULL
);

ALTER TABLE CHAT.TB_ROOM ADD CONSTRAINT FK_SECTOR
    FOREIGN KEY (FK_SECTOR)
    REFERENCES CHAT.TB_SECTOR (ID);
 
ALTER TABLE CHAT.TB_ROOM ADD CONSTRAINT FK_USER_CUSTOMER
    FOREIGN KEY (FK_USER_CUSTOMER)
    REFERENCES AUTH.TB_USER (ID);
 
ALTER TABLE CHAT.TB_ROOM ADD CONSTRAINT FK_USER_EMPLOYEE
    FOREIGN KEY (FK_USER_EMPLOYEE)
    REFERENCES AUTH.TB_USER (ID);
