CREATE TABLE CHAT.TB_MESSAGE (
    ID SERIAL PRIMARY KEY,
    FK_ROOM SERIAL,
    FK_USER SERIAL,
    CONTENT TEXT NOT NULL,
    SENT_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE CHAT.TB_MESSAGE ADD CONSTRAINT FK_ROOM
    FOREIGN KEY (FK_ROOM)
    REFERENCES CHAT.TB_ROOM (ID);
 
ALTER TABLE CHAT.TB_MESSAGE ADD CONSTRAINT FK_USER
    FOREIGN KEY (FK_USER)
    REFERENCES AUTH.TB_USER (ID);
