CREATE TABLE CHAT.TB_ROOM (
    ID SERIAL CONSTRAINT PK_TB_ROOM PRIMARY KEY,
    CODE SERIAL NOT NULL CONSTRAINT UC_TB_ROOM_CODE UNIQUE,
    ROOM_STATUS SMALLINT DEFAULT 0 NOT NULL,
    FK_USER_CUSTOMER INT NOT NULL,
    FK_USER_EMPLOYEE INT,
    FK_SECTOR INT NOT NULL,
    CREATE_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CLOSE_DATETIME TIMESTAMP DEFAULT NULL,
    CONSTRAINT CHK_TB_ROOM_ROOM_STATUS CHECK (
    	(ROOM_STATUS = 0 AND FK_USER_EMPLOYEE IS NULL) OR (ROOM_STATUS BETWEEN 1 AND 4)
    )
);

ALTER TABLE CHAT.TB_ROOM ADD CONSTRAINT FK_SECTOR
    FOREIGN KEY (FK_SECTOR)
    REFERENCES CHAT.TB_SECTOR (ID);
 
ALTER TABLE CHAT.TB_ROOM ADD CONSTRAINT FK_USER_CUSTOMER
    FOREIGN KEY (FK_USER_CUSTOMER)
    REFERENCES AUTH.TB_USER (ID);
 
ALTER TABLE CHAT.TB_ROOM ADD CONSTRAINT FK_USER_EMPLOYEE
    FOREIGN KEY (FK_USER_EMPLOYEE)
    REFERENCES AUTH.TB_USER (ID);
