CREATE TABLE CHAT.TB_MESSAGE (
    ID SERIAL CONSTRAINT PK_TB_MESSAGE PRIMARY KEY,
    FK_ROOM SERIAL NOT NULL,
    FK_USER SERIAL NOT NULL,
    CONTENT_TYPE SMALLINT DEFAULT 0 NOT NULL CONSTRAINT CHK_TB_MESSAGE_CONTENT_TYPE CHECK (CONTENT_TYPE >= 0 AND CONTENT_TYPE <= 3),
    CONTENT TEXT NOT NULL,
    CREATE_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATETIME TIMESTAMP DEFAULT NULL,
    DELETE_DATETIME TIMESTAMP DEFAULT NULL
);

ALTER TABLE CHAT.TB_MESSAGE ADD CONSTRAINT FK_ROOM
    FOREIGN KEY (FK_ROOM)
    REFERENCES CHAT.TB_ROOM (ID);
 
ALTER TABLE CHAT.TB_MESSAGE ADD CONSTRAINT FK_USER
    FOREIGN KEY (FK_USER)
    REFERENCES AUTH.TB_USER (ID);
