CREATE TABLE KANBAN.TB_TASK (
    ID SERIAL CONSTRAINT PK_TB_TASK PRIMARY KEY,
    FK_ROOM SERIAL NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    CREATION_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FK_TASK_PRIORITY SMALLINT DEFAULT 3 NOT NULL
);
 
ALTER TABLE KANBAN.TB_TASK ADD CONSTRAINT FK_ROOM
    FOREIGN KEY (FK_ROOM)
    REFERENCES CHAT.TB_ROOM (ID);
 
ALTER TABLE KANBAN.TB_TASK ADD CONSTRAINT FK_TASK_PRIORITY
    FOREIGN KEY (FK_TASK_PRIORITY)
    REFERENCES KANBAN.TB_TASK_PRIORITY (ID);
