CREATE TABLE KANBAN.TB_TASK_ATTACHMENT (
    ID SERIAL CONSTRAINT PK_TB_TASK_ATTACHMENT PRIMARY KEY,
    FK_TASK INTEGER NOT NULL,
    FILENAME VARCHAR(100),
    CONTENT TEXT NOT NULL
);

ALTER TABLE KANBAN.TB_TASK_ATTACHMENT ADD CONSTRAINT FK_TASK
    FOREIGN KEY (FK_TASK)
    REFERENCES KANBAN.TB_TASK (ID);
