CREATE TABLE KANBAN.TB_STAGE (
    ID SERIAL CONSTRAINT PK_TB_STAGE PRIMARY KEY,
    FK_TASK INTEGER NOT NULL,
    STEP_NUMBER SMALLINT,
    DESCRIPTION TEXT,
    FK_USER_FROM INTEGER NOT NULL,
    FK_USER_TO INTEGER,
    FK_DEPARTMENT_TO INTEGER
);

ALTER TABLE KANBAN.TB_STAGE ADD CONSTRAINT FK_TASK
    FOREIGN KEY (FK_TASK)
    REFERENCES KANBAN.TB_TASK (ID);

ALTER TABLE KANBAN.TB_STAGE ADD CONSTRAINT FK_USER_FROM
    FOREIGN KEY (FK_USER_FROM)
    REFERENCES AUTH.TB_USER (ID);

ALTER TABLE KANBAN.TB_STAGE ADD CONSTRAINT FK_USER_TO
    FOREIGN KEY (FK_USER_TO)
    REFERENCES AUTH.TB_USER (ID);

ALTER TABLE KANBAN.TB_STAGE ADD CONSTRAINT FK_DEPARTMENT_TO
    FOREIGN KEY (FK_DEPARTMENT_TO)
    REFERENCES AUTH.TB_DEPARTMENT (ID);