CREATE TABLE KANBAN.TB_STAGE_ATTACHMENT (
    ID SERIAL CONSTRAINT PK_TB_STAGE_ATTACHMENT PRIMARY KEY,
    FK_STAGE INTEGER NOT NULL,
    FILENAME VARCHAR(100) NOT NULL,
    CONTENT TEXT NOT NULL
);
 
ALTER TABLE KANBAN.TB_STAGE_ATTACHMENT ADD CONSTRAINT FK_STAGE
    FOREIGN KEY (FK_STAGE)
    REFERENCES TB_STAGE (ID);
