auth:
  jwt:
    token:
      secret-key: 17cdl5
      expire-length: 3600000

server:
  port: 8080

spring: 
  application:
    name: help-desk
  jackson:
    time-zone: America/Sao_Paulo
  datasource:
    url: jdbc:postgresql://localhost:5432/hd
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    
springdoc:
  api-docs:
    path: /api-docs
  paths-to-match:
    - /v1/**
  swagger-ui: 
    use-root-path: true
